
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.zfs-forensic]
audit-as-crates-io = true

[policy.zfs-forensic-core]
audit-as-crates-io = true

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.1.9"
criteria = "safe-to-deploy"

[[exemptions.forensicnomicon]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.forensicnomicon-core]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.forensicnomicon-data]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.186"
criteria = "safe-to-deploy"

[[exemptions.lz4_flex]]
version = "0.11.6"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.46"
criteria = "safe-to-deploy"

[[exemptions.ruzstd]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.9"
criteria = "safe-to-deploy"

[[exemptions.simd-adler32]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.119"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.twox-hash]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.20.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.zfs-forensic]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.zfs-forensic-core]]
version = "0.1.0"
criteria = "safe-to-deploy"
